import 'package:flutter/foundation.dart';
import '../data/models/message_model.dart';
import '../data/repositories/message_repository.dart';
import '../services/supabase_service.dart';

class MessageProvider extends ChangeNotifier {
  List<ConversationModel> _conversations = [];
  Map<String, List<MessageModel>> _messages = {};
  bool _isLoading = false;
  String _error = '';

  List<ConversationModel> get conversations => _conversations;
  bool get isLoading => _isLoading;
  String get error => _error;

  int get totalUnreadCount =>
      _conversations.fold(0, (sum, c) => sum + c.unreadCount);

  MessageProvider() {
    _initializeMessages();
  }

  Future<void> _initializeMessages() async {
    try {
      final userId = await SupabaseService.getUserId();
      if (userId != null) {
        await loadConversations(userId);
      }
    } catch (e) {
      print('Error initializing messages: $e');
    }
  }

  Future<void> loadConversations(String userId) async {
    try {
      _isLoading = true;
      _error = '';
      notifyListeners();

      _conversations = await MessageRepository.fetchConversations(userId);
    } catch (e) {
      _error = 'Failed to load conversations: $e';
      print('Error loading conversations: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<List<MessageModel>> getMessages(String conversationId) async {
    try {
      if (!_messages.containsKey(conversationId)) {
        _messages[conversationId] = await MessageRepository.fetchMessages(conversationId);
      }
      return _messages[conversationId] ?? [];
    } catch (e) {
      print('Error getting messages: $e');
      return [];
    }
  }

  Future<void> sendMessage(String conversationId, String content) async {
    if (content.trim().isEmpty) return;

    try {
      final userId = await SupabaseService.getUserId();
      if (userId == null) return;

      // Find conversation to get receiver ID
      final conversation = _conversations.firstWhere(
        (c) => c.id == conversationId,
        orElse: () => throw Exception('Conversation not found'),
      );

      final receiverId = conversation.buyerId == userId 
          ? conversation.sellerId 
          : conversation.buyerId;

      final newMessage = MessageModel(
        id: '', // Will be generated by database
        senderId: userId,
        receiverId: receiverId,
        conversationId: conversationId,
        content: content.trim(),
        timestamp: DateTime.now(),
        isRead: true,
      );

      await MessageRepository.sendMessage(newMessage);

      // Update local messages
      if (!_messages.containsKey(conversationId)) {
        _messages[conversationId] = [];
      }
      _messages[conversationId]!.add(newMessage);

      // Update conversation in list
      final convIndex = _conversations.indexWhere((c) => c.id == conversationId);
      if (convIndex != -1) {
        final conv = _conversations[convIndex];
        _conversations[convIndex] = ConversationModel(
          id: conv.id,
          buyerId: conv.buyerId,
          sellerId: conv.sellerId,
          watchId: conv.watchId,
          watchTitle: conv.watchTitle,
          participantId: conv.participantId,
          participantName: conv.participantName,
          participantImage: conv.participantImage,
          lastMessage: content.trim(),
          lastMessageTime: DateTime.now(),
          unreadCount: 0,
        );
      }

      notifyListeners();
    } catch (e) {
      _error = 'Failed to send message: $e';
      print('Error sending message: $e');
    }
  }

  Future<void> markAsRead(String conversationId) async {
    try {
      await MessageRepository.markConversationAsRead(conversationId);
      
      final convIndex = _conversations.indexWhere((c) => c.id == conversationId);
      if (convIndex != -1) {
        final conv = _conversations[convIndex];
        _conversations[convIndex] = ConversationModel(
          id: conv.id,
          buyerId: conv.buyerId,
          sellerId: conv.sellerId,
          watchId: conv.watchId,
          watchTitle: conv.watchTitle,
          participantId: conv.participantId,
          participantName: conv.participantName,
          participantImage: conv.participantImage,
          lastMessage: conv.lastMessage,
          lastMessageTime: conv.lastMessageTime,
          unreadCount: 0,
        );
        notifyListeners();
      }
    } catch (e) {
      print('Error marking as read: $e');
    }
  }

  Future<void> startNewConversation({
    required String sellerId,
    required String sellerName,
    required String sellerImage,
    required String watchId,
    required String watchTitle,
  }) async {
    try {
      final userId = await SupabaseService.getUserId();
      if (userId == null) return;

      final conversationId = await MessageRepository.createConversation(
        buyerId: userId,
        sellerId: sellerId,
        watchId: watchId,
        watchTitle: watchTitle,
      );

      // Check if conversation already exists in local list
      final existingIndex = _conversations.indexWhere((c) => c.id == conversationId);
      if (existingIndex == -1) {
        _conversations.insert(
          0,
          ConversationModel(
            id: conversationId,
            buyerId: userId,
            sellerId: sellerId,
            watchId: watchId,
            watchTitle: watchTitle,
            participantId: sellerId,
            participantName: sellerName,
            participantImage: sellerImage,
            lastMessage: '',
            lastMessageTime: DateTime.now(),
            unreadCount: 0,
          ),
        );
        notifyListeners();
      }
    } catch (e) {
      _error = 'Failed to start conversation: $e';
      print('Error starting conversation: $e');
    }
  }

  Future<void> refreshConversations() async {
    final userId = await SupabaseService.getUserId();
    if (userId != null) {
      await loadConversations(userId);
    }
  }

  void clearError() {
    _error = '';
    notifyListeners();
  }
}