import 'package:flutter/foundation.dart';
import '../data/models/user_model.dart';
import '../data/models/order_model.dart';
import '../data/repositories/user_repository.dart';
import '../data/repositories/order_repository.dart';
import '../services/supabase_service.dart';

class UserProvider extends ChangeNotifier {
  UserModel? _currentUser;
  List<OrderModel> _orders = [];
  bool _isLoggedIn = false;
  bool _isLoading = false;
  String _error = '';

  UserModel? get currentUser => _currentUser;
  List<OrderModel> get orders => _orders;
  bool get isLoggedIn => _isLoggedIn;
  bool get isLoading => _isLoading;
  String get error => _error;

  UserProvider() {
    _initializeUser();
  }

  Future<void> _initializeUser() async {
    try {
      final userId = await SupabaseService.getUserId();
      if (userId != null) {
        await loadUser(userId);
      }
    } catch (e) {
      print('Error initializing user: $e');
    }
  }

  Future<void> loadUser(String userId) async {
    try {
      _isLoading = true;
      _error = '';
      notifyListeners();

      _currentUser = await UserRepository.fetchUserProfile(userId);
      _orders = await OrderRepository.fetchUserOrders(userId);
      _isLoggedIn = _currentUser != null;
    } catch (e) {
      _error = 'Failed to load user data: $e';
      print('Error loading user: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> updateProfile({
    String? name,
    String? email,
    String? phone,
    String? location,
  }) async {
    if (_currentUser == null) return;

    try {
      _isLoading = true;
      _error = '';
      notifyListeners();

      final updatedUser = _currentUser!.copyWith(
        name: name ?? _currentUser!.name,
        email: email ?? _currentUser!.email,
        phone: phone ?? _currentUser!.phone,
        location: location ?? _currentUser!.location,
      );

      await UserRepository.updateUserProfile(_currentUser!.id, updatedUser);
      _currentUser = updatedUser;
    } catch (e) {
      _error = 'Failed to update profile: $e';
      print('Error updating profile: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> createOrder({
    required String watchId,
    required String watchTitle,
    required String watchImage,
    required String sellerId,
    required String sellerName,
    required double price,
    required String shippingAddress,
  }) async {
    if (_currentUser == null) return;

    try {
      final order = OrderModel(
        id: '', // Will be generated by database
        watchId: watchId,
        watchTitle: watchTitle,
        watchImage: watchImage,
        buyerId: _currentUser!.id,
        sellerId: sellerId,
        sellerName: sellerName,
        price: price,
        orderDate: DateTime.now(),
        status: OrderStatus.pending,
        shippingAddress: shippingAddress,
      );

      await OrderRepository.createOrder(order);
      
      // Refresh orders
      _orders = await OrderRepository.fetchUserOrders(_currentUser!.id);
      notifyListeners();
    } catch (e) {
      _error = 'Failed to create order: $e';
      print('Error creating order: $e');
      rethrow;
    }
  }

  Future<void> refreshOrders() async {
    if (_currentUser == null) return;

    try {
      _orders = await OrderRepository.fetchUserOrders(_currentUser!.id);
      notifyListeners();
    } catch (e) {
      print('Error refreshing orders: $e');
    }
  }

  void logout() {
    _currentUser = null;
    _orders = [];
    _isLoggedIn = false;
    _error = '';
    notifyListeners();
  }

  void login() {
    _initializeUser();
  }

  void clearError() {
    _error = '';
    notifyListeners();
  }
}